global:
  resolve_timeout: 5m

route:
  receiver: heal8s-webhook
  group_by: ['alertname', 'cluster', 'namespace']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h

receivers:
  - name: heal8s-webhook
    webhook_configs:
      - url: http://heal8s-operator.heal8s-system.svc.cluster.local:8082/webhooks/alertmanager
        send_resolved: false
        http_config:
          follow_redirects: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'cluster', 'namespace']
