apiVersion: v1
kind: Service
metadata:
  name: {{ include "heal8s.fullname" . }}-operator
  namespace: {{ include "heal8s.namespace" . }}
  labels:
    {{- include "heal8s.labels" . | nindent 4 }}
    app.kubernetes.io/component: operator
spec:
  type: {{ .Values.operator.webhook.service.type }}
  ports:
  - name: webhook
    port: {{ .Values.operator.webhook.service.port }}
    targetPort: webhook
    protocol: TCP
  {{- if .Values.operator.metrics.enabled }}
  - name: metrics
    port: {{ .Values.operator.metrics.port }}
    targetPort: metrics
    protocol: TCP
  {{- end }}
  selector:
    {{- include "heal8s.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: operator
