kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: heal8s-dev
nodes:
  - role: control-plane
    extraPortMappings:
      # Alertmanager webhook
      - containerPort: 30082
        hostPort: 8082
        protocol: TCP
      # Prometheus (optional)
      - containerPort: 30090
        hostPort: 9090
        protocol: TCP
      # Alertmanager UI (optional)
      - containerPort: 30093
        hostPort: 9093
        protocol: TCP
